apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: website-https
  namespace: crimelabs-dev
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`crimelabs.dev`)
      kind: Rule
      services:
        - name: website
          port: 80
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: website-http
  namespace: crimelabs-dev
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`crimelabs.dev`)
      kind: Rule
      services:
        - name: website
          port: 80
      middlewares:
        - name: redirect-to-https
