apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: website-https
  namespace: accelome
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`accelome.de`)
      kind: Rule
      services:
        - name: sveltekit-app
          port: 80
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: website-http
  namespace: accelome
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`accelome.de`)
      kind: Rule
      services:
        - name: sveltekit-app
          port: 80
      middlewares:
        - name: redirect-to-https
